# Generated by Django 6.0.3 on 2026-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID сессии')),
                ('user_message', models.TextField(verbose_name='Сообщение пользователя')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('response_source', models.CharField(blank=True, choices=[('knowledge_base', 'База знаний'), ('faq', 'FAQ из БД'), ('ai', 'Yandex GPT'), ('fallback', 'Запасной ответ')], max_length=50, verbose_name='Источник ответа')),
                ('response_time', models.FloatField(default=0, verbose_name='Время ответа (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Аналитика чата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL страницы')),
                ('page_title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок страницы')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Откуда пришёл')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Поисковый запрос')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество результатов')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поиска')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('pages_viewed', models.IntegerField(default=0, verbose_name='Просмотрено страниц')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='Первое посещение')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Последнее посещение')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-last_visit'],
            },
        ),
    ]
